name: Military-Grade CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
  schedule:
    - cron: '0 3 * * *' # Run daily at 3 AM UTC

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  security_scan:
    name: Military-Grade Security Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: CodeQL Initialization
        uses: github/codeql-action/init@v2
        with:
          languages: 'javascript, python, HTML'

      - name: Perform Static Security Scan
        uses: github/codeql-action/analyze@v2

      - name: Dependency Vulnerability Scan
        run: |
          sudo apt-get install -y trivy
          trivy fs --severity HIGH,CRITICAL .

  build_and_test:
    name: Build and Test Code
    runs-on: ubuntu-latest
    needs: security_scan

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  compliance_check:
    name: Military-Grade Compliance Checks
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Compliance Tools
        run: |
          pip install bandit
          npm install -g snyk

      - name: Run Python Security Check
        run: bandit -r .

      - name: Run JavaScript Security Check
        run: snyk test

  deploy:
    name: Secure Deployment
    runs-on: ubuntu-latest
    needs: compliance_check
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Static Dashboard to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
